apiVersion: apps/v1
kind: Deployment
metadata:
  name: familytree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: familytree
  template:
    metadata:
      labels:
        app: familytree
    spec:
      containers:
        - name: familytree
          image: familytree:latest
          ports:
            - containerPort: 8080
